apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: engeneer
  labels:
    rbac.example.com/engeneer: "true"
rules:
- apiGroups: [""]
  resources: ["nodes", "pods", "deployments", "namespaces"]
  verbs: ["get", "list", "watch", "create", "update", "edit", "delete", "exec"]